# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e02a39f36cb037eeafd01a470d0f7dd1cde115a227077a71e2ffc228fe8a20e4ce816b03a789ab03f9e2ab142c4980a452cf10739d18791b0794eab0d11c5800

test:
  secret_key_base: b9b85ea3d1ed989de462ce67ce0008f204b84565573601ddb5d095d34195143d1018a39556051b5b5fd9487b149088dbf30610a281fdd54e6218dc92fd99cc6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
